@Neova.Catalog.API_HostAddress = http://localhost:5253

GET {{Neova.Catalog.API_HostAddress}}/api/products
Accept: application/json

###
POST {{Neova.Catalog.API_HostAddress}}/api/products/discount
Content-Type: application/json

{
  "producId": "dca71cbc-83ea-4eda-b719-d814e86d3e52",
  "discountRate": 0.10
}



